name: CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:  # allow manual runs

jobs:
  build-api:
    name: Build & Test .NET API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore packages (cache NuGet)
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/backend/**/package.lock.json', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet restore
        run: dotnet restore backend/TradingDashboard.slnx

      - name: dotnet build
        run: dotnet build backend/TradingDashboard.slnx --configuration Release --no-restore

      - name: dotnet test
        run: dotnet test backend/Tests/Tests.csproj --no-build --configuration Release